config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/auth/facebook/callback' => 'sessions#fbcreate'
  post '/logout', to: 'sessions#destroy'
  get '/search', to: 'application#search'
  post '/search', to: 'application#result'
  get '/price_sort', to: 'listings#price_sort'

  resources :users do
    resources :listings, only: [:new, :edit, :show, :destroy]
  end
  resources :albums do
    get 'by_artist/:artist' => :artist, on: :collection
  end
  resources :listings, only: [:index, :create, :update]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/album.rb
class Album < ApplicationRecord
  validates :artist, presence: true, uniqueness: { scope: [:title, :release_year] }
  validates :title, presence: true, uniqueness: { scope: [:artist, :release_year] }
  validates :release_year, presence: true, uniqueness: { scope: [:artist, :title] }
  validates :genre, presence: true

  has_many :listings
  has_many :users, :through => :listings

  include ::AlbumConcerns

  scope :all_by_artist, -> (artist) { where(artist: artist) }
  scope :discog_order, -> { order(:release_year, :title) }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/album_concerns.rb
module AlbumConcerns
  extend ActiveSupport::Concern

  def artist_with_title
    "#{artist} - #{title}"
  end
end

app/models/listing.rb
class Listing < ApplicationRecord
  validates :condition, presence: true
  validates :price, numericality: { greater_than: 0 }
  validates :user_id, presence: true
  validates :album_id, presence: true
  serialize :notes, JSON

  belongs_to :user
  belongs_to :album

  scope :listing_low_to_high, -> { order(:price) }

  NOTES = [
    'Sealed', '1st Pressing', 'Colored Vinyl', 'Picture Disc',
    'Limited Run', 'Promotional Release', 'Import'
  ]
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true
  has_secure_password
  validates :password, presence: true

  has_many :listings
  has_many :albums, :through => :listings
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :require_login, only: [:new, :show, :artist]

  def new
    @album = Album.new
  end

  def create
    @album = Album.new(album_params)
    if @album.save
      redirect_to new_user_listing_path(current_user)
    else
      render :new
    end
  end

  def show
    @album = Album.find(params[:id])
    @listings = @album.listings
    respond_to do |f|
      f.html {render :show}
      f.json {render json: @album}
    end
  end

  def artist
    @slug = params[:artist]
    Album.all.each do |album|
      if @slug == album.artist.parameterize
        @artist = album.artist
        @artist_albums = Album.all_by_artist(@artist).discog_order
      end
    end
  end

  private

  def album_params
    params.require(:album).permit(:artist, :title, :release_year, :genre)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :require_login, only: [:show, :edit]
  helper_method :logged_in?, :current_user
  skip_before_action :verify_authenticity_token

  def search
  end

  def result
    @artist = params[:search]
    if Album.all.group_by(&:artist).include?(@artist)
      redirect_to "/albums/by_artist/#{@artist.parameterize}"
    else
      flash[:error] = "Artist not found"
      redirect_back(fallback_location: root_path)
    end
  end

  private

  def require_login
    if !logged_in?
      redirect_to root_path
    end
  end

  def logged_in?
    session[:user_id]
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  include ListingsHelper
  before_action :require_permission, only: [:edit]

  def index
    @listings = Listing.all
    respond_to do |f|
      f.html {render :index}
      f.json {render json: @listings}
    end
  end

  def new
    @listing = Listing.new
  end

  def create
    @listing = Listing.new(listing_params)
    @listing.user_id = current_user.id if current_user
    if @listing.save
      redirect_to user_listing_path(current_user, @listing)
    else
      render :new
    end
  end

  def edit
    @listing = Listing.find(params[:id])
  end

  def update
    @listing = Listing.find(params[:id])
    if @listing.update(listing_params)
      redirect_to user_listing_path(current_user, @listing)
    else
      render :edit
    end
  end

  def show
    @listing = Listing.find(params[:id])
  end

  def destroy
    @listing = Listing.find(params[:id])
    if @listing.user == current_user
      @listing.destroy
      redirect_to user_path(current_user)
    end
  end

  def price_sort
    @listings = Listing.listing_low_to_high
  end

  private

  def listing_params
    params.require(:listing).permit(:condition, :price, { notes: [] }, :user_id, :album_id)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
    redirect_to root_path if current_user
  end

  def create
    @user = User.find_by(username: params[:username])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to root_path
    else
      flash[:error] = 'Username or password was incorrect. Please try agin.'
      redirect_to login_path
    end
  end

  def fbcreate
    @user = User.find_or_create_by(uid: auth['uid']) do |u|
      u.username = auth['info']['name']
      u.email = auth['info']['email']
      u.password = auth['uid']
    end
    session[:user_id] = @user.id
    redirect_to root_path
  end

  def destroy
    session.delete :user_id
    redirect_to root_path
  end

  private

  def auth
    request.env['omniauth.auth']
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
    @listings = Listing.all
    @recent_listings = @listings.reverse[0..4]
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
    redirect_to root_path if current_user
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to @user
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    @listings = @user.listings
    respond_to do |f|
      f.html {render :show}
      f.json {render json: @listings}
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def inline_errors(model, attribute)
    result = ""
    if model.errors[attribute].any?
      model.errors[attribute].each do |message|
        result += "<li>#{message}</li>".html_safe
      end
    end
    "<ul>#{result}</ul>".html_safe
  end

end

app/helpers/listings_helper.rb
module ListingsHelper

  def require_permission
    @listing = Listing.find(params[:id])
    if current_user != @listing.user
      redirect_to user_listing_path(@listing.user, @listing)
    end
  end

end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/albums/_form.html.erb
<%= form_for(@album) do |f| %>
  <%= f.label :artist %>:<br>
  <%= f.text_field :artist %>
  <% @album.errors[:artist].each do |error| %>
    <div id='error_explanation'><%= inline_errors(@album, :artist) %></div>
  <% end %><br><br>
  <%= f.label :title %>:<br>
  <%= f.text_field :title %>
  <% @album.errors[:title].each do |error| %>
    <div id='error_explanation'><%= inline_errors(@album, :title) %></div>
  <% end %><br><br>
  <%= f.label :release_year, 'Release Year' %>:<br>
  <%= f.text_field :release_year %>
  <% @album.errors[:release_year].each do |error| %>
    <div id='error_explanation'><%= inline_errors(@album, :release_year) %></div>
  <% end %><br><br>
  <%= f.label :genre %>:<br>
  <%= f.text_field :genre %>
  <% @album.errors[:genre].each do |error| %>
    <div id='error_explanation'><%= inline_errors(@album, :genre) %></div>
  <% end %><br><br>
  <%= f.submit 'Create Album' %>
<% end %>

app/views/albums/artist.html.erb
<center><h1><div id="album-artist"><%= @artist %></div></h1></center>

<p><h2>Albums:</h2>
<p><div class="margin"><div id="artist-albums"><% @artist_albums.each do |album| %>
  <h3><%= link_to album.title, album_path(album) %></h3>
  <small>Released: <%= album.release_year %></small><br><br>
<% end %></div></div>

<button id='new-album-form-btn'>Add New Album</button>
<div id="new-album-form"></div>

app/views/albums/new.html.erb
<h2>Add Album to Database</h2>

<%= render 'form' %>

app/views/albums/show.html.erb
<div id="show-album"></div>
<%= render 'listings/listings' %>

<%= button_to 'Add New Listing', new_user_listing_path(current_user), method: :get %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="no-js" lang="en">
  <head>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="wrapper">
      <%= yield %>
      <footer class="branding">
        <% if logged_in? %>
          <%= form_tag :search do %>
            <%= text_field_tag :search %>
            <%= submit_tag 'Search by Artist' %>
            <% if flash[:error] %>
              <div id='error_explanation'><small><%= flash[:error] %></small></div>
            <% end %>
          <% end %><br>

          Currently logged in as: <%= link_to current_user.username, user_path(current_user) %>
          <%= button_to 'Log Out', logout_path, method: :post %><br>
        <% end %>
        <p><small>&copy; 2019 <strong><a href="/">Vinyl Swap</a></strong></small>
      </footer>
    </div>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
  </body>
</html>

app/views/listings/_form.html.erb
<%= f.label :condition %>:<br>
<%= f.radio_button :condition, "Mint" %> <small>Mint</small>
<%= f.radio_button :condition, "Near Mint" %> <small>Near Mint</small>
<%= f.radio_button :condition, "Very Good" %> <small>Very Good</small>
<%= f.radio_button :condition, "Good" %> <small>Good</small>
<%= f.radio_button :condition, "Poor" %> <small>Poor</small>
<% @listing.errors[:condition].each do |error| %>
  <div id='error_explanation'><%= inline_errors(@listing, :condition) %></div>
<% end %><br><br>
<%= f.label :price %>:<br>
<%= f.number_field :price %>
<% @listing.errors[:price].each do |error| %>
  <div id='error_explanation'><%= inline_errors(@listing, :price) %></div>
<% end %><br><br>
<%= f.label :notes, "Additional Notes:" %><br>
<% Listing::NOTES.each do |note| %>
  <%= f.check_box :notes, { multiple: true }, note, nil %>
  <small> <%= note %></small>
<% end %><br><br>

app/views/listings/_listings.html.erb
<% if @listings.empty? %>
  None yet!<br><br>
<% else %>
  <div class="margin"><% @listings.each do |listing| %>
    <% if @album %>
      <%= link_to "#{listing.condition} - $#{listing.price}", user_listing_path(listing.user, listing) %><br>
      <small>Sold by <%= link_to "#{listing.user.username}", user_path(listing.user) %></small><br>
    <% end %>
    <br>
  <% end %></div>
<% end %>

app/views/listings/edit.html.erb
<h2><%= @listing.album.artist %> - <%= @listing.album.title %></h2>
<%= form_for([@user, @listing]) do |f| %>
  <%= render partial: 'form', locals: { :f => f} %>
  <%= f.submit 'Edit Listing' %>
<% end %>

app/views/listings/new.html.erb
<h2>Create New Listing</h2>

<%= form_for([@user, @listing]) do |f| %>
  Choose an album from database to list:<br>
  <%= collection_select(:listing, :album_id, Album.order(:artist), :id, :artist_with_title, prompt: true) %>
  <% @listing.errors[:album_id].each do |error| %>
    <div id='error_explanation'><%= inline_errors(@listing, :album_id) %></div>
  <% end %><br>
  <small><%= link_to 'or add a new album to database first', new_album_path %></small><br><br>
  <%= render partial: 'form', locals: { :f => f} %>
  <%= f.submit 'Create Listing' %>
<% end %>

app/views/listings/price_sort.html.erb
<h2>Lowest Price Listings</h2>

<% @listings.each do |listing| %>
  <%= link_to user_listing_path(listing.user, listing) do %>
    <%= listing.album.artist %> - <%= listing.album.title %><br>
  <% end %>
    <small>Sold by <%= link_to "#{listing.user.username}", user_path(listing.user) %></small><br>
    <small><%= listing.condition %> - $<%= listing.price %></small><br><br>
<% end %>

app/views/listings/show.html.erb
<h2><%= link_to @listing.album.artist, "/albums/by_artist/#{@listing.album.artist.parameterize}" %> - <%= link_to @listing.album.title, album_path(@listing.album) %></h2>
<h3>Sold by <%= link_to "#{@listing.user.username}", user_path(@listing.user) %></h3>

<br><b>Condition: </b><%= @listing.condition %><br>
<b>Price:</b> $<%= @listing.price %><br>
<% if @listing.notes != nil %>
  <b>Additional Notes:</b><br>
  <div class="margin"><% @listing.notes.each do |note| %>
   <%= note %><br>
  <% end %></div>
<% end %>

<br>If you would like to purchase this item or have any questions then please email: <%= mail_to @listing.user.email %><br><br>

<% if @listing.user == current_user %>
  <%= button_to 'Edit Listing', edit_user_listing_path(current_user, @listing), method: :get %>
  <%= button_to 'Delete Listing', user_listing_path(current_user, @listing), method: :delete %>
<% end %>

app/views/static_pages/home.html.erb
<center><h1>Welcome to Vinyl Swap</h1></center>

<% if !logged_in? %>
  <center><br><%= button_to 'Log In', login_path, method: :get %>
  <%= button_to 'Log In via Facebook', '/auth/facebook', method: :get %>
  <%= button_to 'Sign Up', signup_path, method: :get %></center>
<% else %>
  <p><h2>Recent Listings:</h2>
  <div class='margin' id='recent-listings'><% @recent_listings.each do |listing| %>
    <%= link_to user_listing_path(listing.user, listing) do %>
      <%= listing.album.artist %> - <%= listing.album.title %><br>
    <% end %>
      <small>Sold by <%= link_to "#{listing.user.username}", user_path(listing.user) %></small><br>
      <small><%= listing.condition %> - $<%= listing.price %></small><br><br>
  <% end %></div>
  <button id='more-listings'>See More</button>
<% end %>

app/views/users/new.html.erb
<%= form_for(@user) do |f| %>
  <%= f.label :username, 'Username:' %><br>
  <%= f.text_field :username %>
  <% @user.errors[:username].each do |error| %>
    <div id='error_explanation'><%= inline_errors(@user, :username) %></div>
  <% end %><br><br>
  <%= f.label :email, 'Email:' %><br>
  <%= f.text_field :email %>
  <% @user.errors[:email].each do |error| %>
    <div id='error_explanation'><%= inline_errors(@user, :email) %></div>
  <% end %><br><br>
  <%= f.label :password, 'Password:' %><br>
  <%= f.password_field :password %>
  <% @user.errors[:password].each do |error| %>
    <div id='error_explanation'><%= inline_errors(@user, :password) %></div>
  <% end %><br><br>
  <%= f.submit 'Create Account' %>
<% end %>

app/views/users/show.html.erb
<% if @user == current_user %>
  <center><h1>Welcome, <%= @user.username %></h1></center>
<% else %>
  <center><h1><%= @user.username %>'s Collection</h1></center>
<% end %>

<h2>Records for sale:</h2>
<div class="margin" id="user-listings"></div>
<button id='sort-price-btn'>Sort Low to High</button>

<% if @user == current_user %>
  <%= button_to 'Add New Listing', new_user_listing_path(@user), method: :get %>
<% end %>